#! /usr/bin/php
<?php

use Aura\Cli\CliFactory;
use LoveSay\Note;
use LoveSay\NoteRepository;

require __DIR__ . '/bootstrap.php';

$cli_factory = new CliFactory;
$stdio = $cli_factory->newStdio();

$intro_text = 'lovesay: ' . \LoveSay\Description::express();
$stdio->outln($intro_text);

$note_api = new \LoveSay\API\FileNotes(__DIR__ . '/say.sqlite3');
$note_repository = new NoteRepository($note_api);

$stdio->out('Add a message: ');
$message = trim($stdio->in());

if (!empty($message)) {
    $note = new Note($message);
    $note_id = $note_repository->addNote($note);
    $stdio->outln("Added note: [id: {$note_id}] {$message}");
} else {
    $stdio->outln("No message added");
}

//function loadFile($filename) {
//    $say = include $filename;
//    foreach ($say as $message) {
//        $note = new Note($message);
//        $note_id = $note_repository->addNote($note);
//        $stdio->outln("Added note: [id: {$note_id}] {$message}");
//    }
//}
