#! /usr/bin/php
<?php

use Aura\Cli\CliFactory;
use LoveSay\API\Notes;
use LoveSay\NoteRepository;
use LoveSay\Originator;
use LoveSay\Persistence\Sqlite\SqliteNotesStorage;

require __DIR__ . '/bootstrap.php';

$cli_factory = new CliFactory;
$stdio = $cli_factory->newStdio();

$intro_text = 'lovesay: ' . \LoveSay\Description::express();
$stdio->outln($intro_text);

$originator = new Originator('me');
$note_api = new Notes($originator, new SqliteNotesStorage(__DIR__ . '/say.sqlite3'));
$note_repository = new NoteRepository($note_api);

$say = include __DIR__ . '/say.php';
foreach ($say as $message) {
    $note = $note_repository->createNote($message);
    $note_id = $note_repository->addNote($note);
    $stdio->outln("Added note: [id: {$note_id}] {$message}");
}

$stdio->out('Add a message: ');
$message = trim($stdio->in());

if (!empty($message)) {
    $note = $note_repository->createNote($message);
    $note_id = $note_repository->addNote($note);
    $stdio->outln("Added note: [id: {$note_id}] {$message}");
} else {
    $stdio->outln("No message added");
}

//function loadFile($filename) {
//    $say = include $filename;
//    foreach ($say as $message) {
//        $note = $note_repository->createNote($message);
//        $note_id = $note_repository->addNote($note);
//        $stdio->outln("Added note: [id: {$note_id}] {$message}");
//    }
//}
