#! /usr/bin/php
<?php

use Aura\Cli\CliFactory;
use LoveSay\API\Notes;
use LoveSay\Note;
use LoveSay\Originator;
use LoveSay\Persistence\Sqlite\SqliteNotesStorage;

require __DIR__ . '/bootstrap.php';

$cli_factory = new CliFactory;
$stdio = $cli_factory->newStdio();

$intro_text = 'lovesay: ' . \LoveSay\Description::express();
$stdio->outln($intro_text);

$originator = new Originator('me');
$note_api = new Notes($originator, new SqliteNotesStorage(__DIR__ . '/say.sqlite3'));

$stdio->out('Add a note: ');
$message = trim($stdio->in());

if (!empty($message)) {
    $note = new Note($originator, $message);
    $note_id = $note_api->putNote($note);
    $stdio->outln("Added note: [id: {$note_id}] {$message}");
} else {
    $stdio->outln("No message added");
}

//function loadFile($filename) {
//    $say = include $filename;
//    foreach ($say as $message) {
//        $note = new Note($originator, $message);
//        $note_id = $note_api->putNote($note);
//        $stdio->outln("Added note: [id: {$note_id}] {$message}");
//    }
//}
