#! /usr/bin/php
<?php

use Aura\Cli\CliFactory;
use LoveSay\API\Notes;
use LoveSay\Originator;
use LoveSay\Persistence\Sqlite\SqliteNotesStorage;

require __DIR__ . '/bootstrap.php';

$cli_factory = new CliFactory;
$stdio = $cli_factory->newStdio();
$context = $cli_factory->newContext($GLOBALS);

$getopt = $context->getopt(array('all,a'));

$intro_text = 'lovesay: ' . \LoveSay\Description::express();
$stdio->outln($intro_text);

$originator = new Originator('me');
$note_api = new Notes($originator, new SqliteNotesStorage(__DIR__ . '/say.sqlite3'));

if ($getopt->get('-a')) {
    $notes = $note_api->getAllNotes();
    foreach ($notes as $note) {
        $view_count = $getopt->get('-c', false) ? " [{$note->viewCount()}]" : '';
        $stdio->outln($note . $view_count);
    }
} else {
    $freshness = new \LoveSay\Freshness\True();
    $note = $note_api->viewNote($freshness);
    $view_count = $getopt->get('-c', false) ? " [{$note->viewCount()}]" : '';
    $stdio->outln($note . $view_count);
}
