#! /usr/bin/php
<?php

use Aura\Cli\CliFactory;
use LoveSay\API\NoteReaderService;
use LoveSay\Originator;
use LoveSay\Persistence\Sqlite\SqliteNotesStorage;
use LoveSay\Recipient;
use LoveSay\Relationship;

require dirname(__DIR__) . '/bootstrap.php';

$cli_factory = new CliFactory;
$stdio = $cli_factory->newStdio();
$context = $cli_factory->newContext($GLOBALS);

$getopt = $context->getopt(array('n:', 'c'));

$intro_text = 'lovesay: ' . \LoveSay\Description::express();
$stdio->outln($intro_text);

$storage = new SqliteNotesStorage(dirname(__DIR__) . '/say.sqlite3');
$originator = new Originator('me');
$recipient = new Recipient('you');
$relationship = new Relationship($originator->getKey(), $recipient->getKey());

$note_reader_api = new NoteReaderService($relationship, $storage);

if ($note_key = $getopt->get('-n', false)) {
    $note = $note_reader_api->readNote($note_key);
    if (is_null($note)) {
        $stdio->outln("Your love is enduring. The note seems to be missing.");
        exit;
    }
    $view_count = $getopt->get('-c', false) ? " [{$note->getViewCount()}]" : '';
    $stdio->outln($note . $view_count);
}