#! /usr/bin/php
<?php

use Aura\Cli\CliFactory;
use LoveSay\API\NoteWriterService;
use LoveSay\Note;
use LoveSay\Originator;
use LoveSay\Persistence\Sqlite\SqliteNotesStorage;
use LoveSay\Recipient;
use LoveSay\Relationship;

require dirname(__DIR__) . '/bootstrap.php';

$cli_factory = new CliFactory;
$stdio = $cli_factory->newStdio();
$context = $cli_factory->newContext($GLOBALS);

$getopt = $context->getopt(array('r:', 'n:', 'a', 'c', 'i'));

$intro_text = 'lovesay: ' . \LoveSay\Description::express();
$stdio->outln($intro_text);

$storage_filename = dirname(__DIR__) . '/say.sqlite3';
$storage = new SqliteNotesStorage($storage_filename);
$originator = new Originator('me');
$recipient = new Recipient('you');
$relationship = new Relationship($originator->getKey(), $recipient->getKey());

$note_writer_api = new NoteWriterService($relationship, $storage);

if ($import_filename = $getopt->get('-r')) {
    if (!is_readable($import_filename)) {
        $stdio->errln('Could not read import file');
        exit;
    }
    unlink($storage_filename);
    $note_writer_api = new NoteWriterService($relationship, new SqliteNotesStorage($storage_filename));
    $say = include $import_filename;
    foreach ($say as $message) {
        $note = new Note($relationship->getKey(), $message);
        $note_key = $note_writer_api->putNote($note);
        $stdio->outln("Added note: [key: {$note_key}] {$message}");
    }
} elseif ($getopt->get('-n')) {
    $stdio->out('Add a note: ');
    $message = trim($stdio->in());

    if (!empty($message)) {
        $note = new Note($relationship->getKey(), $message);
        $note_key = $note_writer_api->putNote($note);
        $stdio->outln("Added note: [key: {$note_key}] {$message}");
    } else {
        $stdio->outln("No message added");
    }
} elseif ($getopt->get('-a', false)) {
    $notes = $note_writer_api->getAllNotes();
    foreach ($notes as $note) {
        $id = $getopt->get('-i', false) ? "[{$note->getKey()}] " : '';
        $view_count = $getopt->get('-c', false) ? " [{$note->getViewCount()}]" : '';
        $stdio->outln($id . $note . $view_count);
    }
}